require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end

# The commands that are available to us seen through rake -T are made available to us by require 'sinatra/activerecord/rake'
# To add a column we can use migrations to be able to manipulate existing tables
# Best practice is creating new migrations to modify the existing tables.